# Generated by Django 5.2.7 on 2025-11-04 18:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_fecha_actualizacion_producto_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del carrito')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última modificación del carrito')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente propietario del carrito (null para carritos de sesión anónima)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades del producto', validators=[django.core.validators.MinValueValidator(1)])),
                ('carrito', models.ForeignKey(help_text='Carrito al que pertenece este item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.carrito')),
                ('producto', models.ForeignKey(help_text='Producto agregado al carrito', on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='core.producto')),
            ],
            options={
                'verbose_name': 'Item de Carrito',
                'verbose_name_plural': 'Items de Carrito',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['cliente'], name='core_carrit_cliente_afccb7_idx'),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['fecha_actualizacion'], name='core_carrit_fecha_a_cf8a21_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcarrito',
            index=models.Index(fields=['carrito', 'producto'], name='core_itemca_carrito_7446ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto')},
        ),
    ]
