# Generated by Django 5.2.7 on 2025-11-05 06:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carrito_itemcarrito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del pedido')),
                ('numero_pedido', models.CharField(help_text='Número único del pedido para seguimiento', max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual del pedido', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del pedido (sin impuestos ni envío)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Impuestos aplicados al pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('coste_entrega', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coste de envío del pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado al pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, help_text='Total final del pedido', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo_pago', models.CharField(choices=[('tarjeta_credito', 'Tarjeta de Crédito'), ('stripe', 'Stripe')], help_text='Método de pago utilizado', max_length=20)),
                ('direccion_envio', models.TextField(help_text='Dirección completa de envío del pedido')),
                ('telefono', models.CharField(help_text='Teléfono de contacto para el envío', max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización del pedido')),
                ('cliente', models.ForeignKey(help_text='Cliente que realizó el pedido', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de unidades del producto', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto al momento de la compra', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total', models.DecimalField(decimal_places=2, help_text='Total de este item (precio_unitario * cantidad)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('producto', models.ForeignKey(help_text='Producto incluido en el pedido', on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='core.producto')),
                ('pedido', models.ForeignKey(help_text='Pedido al que pertenece este item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='core_pedido_cliente_bea0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_pedido'], name='core_pedido_numero__dc492d_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='core_pedido_estado_404470_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_creacion'], name='core_pedido_fecha_c_26bdca_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido', 'producto'], name='core_itempe_pedido__2d3adb_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['producto'], name='core_itempe_product_2ec2bd_idx'),
        ),
    ]
