# Generated by Django 5.2.7 on 2025-11-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='pedido',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='ID del PaymentIntent de Stripe', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='ID de la sesión de Checkout de Stripe', max_length=200, null=True),
        ),
    ]
