# Generated by Django 5.2.7 on 2025-11-11 22:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_pedido_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tracking_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para seguimiento de pedido sin cuenta', unique=True),
        ),
    ]
