# Generated by Django 5.2.7 on 2025-11-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedido_tracking_token'),
        ('core', '0009_productos_iniciales'),
    ]

    operations = [
    ]
