# Generated by Django 5.2.7 on 2025-11-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_cliente_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
            ],
        ),
    ]
